let x = 4;

try {
    console.log(y*3);
}catch(err){
    console.log("Error Fuck");
}finally{
    console.log(x*3);
}